### ISSUE TITLE
Readme link

### ISSUE THREAD

**Issue by hughbris** [Karmalakas/grav-plugin-translate-date#10]
Haven't actually tried this but looks like a very handy plugin, and thank you for documenting it well! I may be able to use this plugin to solve some problems in my [Quando plugin](https://github.com/hughbris/grav-plugin-quando).

I noticed the link from [Grav downloads](https://getgrav.org/downloads/plugins) to the README is broken. I think if you don't supply a `readme` property in `blueprints.yaml`, it makes up a URL based on a `develop` branch, which you don't have. So you could fix this by either creating this branch or by providing the correct link in your plugin blueprint.

**Comment by Karmalakas** [comment]
Oh, I see it links to `develop` branch instead of `main`. Thanks for noticing.
I'll fix this at some point when I have a bit of time :) It's a minor inconvenience after all
